wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0rc4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1658793882
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.0rc4
      8:
      - 5
allowed_categories:
  desc: null
  value: ''
arch:
  desc: null
  value: vae
balanced_data:
  desc: null
  value: false
base_pose_weight:
  desc: null
  value:
  - 1000.0
  - 1000.0
  - 1000.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
batch_size:
  desc: null
  value: 16
beta1:
  desc: null
  value: 0.9
blacklisted_categories:
  desc: null
  value: ''
checkpoints_dir:
  desc: null
  value: ./checkpoints
confidence_weight:
  desc: null
  value: 1.0
continue_train:
  desc: null
  value: false
dataset_root_folder:
  desc: null
  value: /home/jens/Documents/datasets/grasping/unified_grasp_data/
dataset_split:
  desc: null
  value: train
depth_noise:
  desc: null
  value: 0.0
epoch_count:
  desc: null
  value: 1
gpu_ids:
  desc: null
  value:
  - 0
grasp_perturb_copies:
  desc: null
  value: 3
grasps_folder_name:
  desc: null
  value: grasps
grasps_ratio:
  desc: null
  value: 1.0
gripper:
  desc: null
  value: panda
gripper_pc_npoints:
  desc: null
  value: -1
init_gain:
  desc: null
  value: 0.02
init_type:
  desc: null
  value: normal
is_train:
  desc: null
  value: true
kl_loss_weight:
  desc: null
  value: 0.01
latent_size:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0002
lr_decay_iters:
  desc: null
  value: 50
lr_policy:
  desc: null
  value: lambda
max_dataset_size:
  desc: null
  value: .inf
merge_pcs_in_vae_encoder:
  desc: null
  value: 0
model_scale:
  desc: null
  value: 1
name:
  desc: null
  value: vae_lr_0002_bs_16_scale_1_npoints_128_radius_02_latent_size_3
niter:
  desc: null
  value: 100
niter_decay:
  desc: null
  value: 2000
no_vis:
  desc: null
  value: false
npoints:
  desc: null
  value: 1024
num_grasp_clusters:
  desc: null
  value: 32
num_grasps_per_object:
  desc: null
  value: 16
num_input_pointcloud_points:
  desc: null
  value: 1024
num_objects_per_batch:
  desc: null
  value: 1
num_threads:
  desc: null
  value: 3
objects:
  desc: null
  value:
  - 003_cracker_box
  - 004_sugar_box
occlusion_dropout_rate:
  desc: null
  value: 0
occlusion_nclusters:
  desc: null
  value: 0
override_saved:
  desc: null
  value: false
pc_noise_variance:
  desc: null
  value: 0.0
phase:
  desc: null
  value: train
pointnet_nclusters:
  desc: null
  value: 128
pointnet_radius:
  desc: null
  value: 0.02
print_freq:
  desc: null
  value: 100
run_test_freq:
  desc: null
  value: 5
save_dir:
  desc: null
  value: ./checkpoints/vae_lr_0002_bs_16_scale_1_npoints_128_radius_02_latent_size_3/1658793886.6549911
save_epoch_freq:
  desc: null
  value: 10
save_latest_freq:
  desc: null
  value: 2500
seed:
  desc: null
  value: null
serial_batches:
  desc: null
  value: false
skip_error:
  desc: null
  value: false
splits_folder_name:
  desc: null
  value: splits
test_ratio:
  desc: null
  value: 0.01
use_uniform_quaternions:
  desc: null
  value: 0
use_wandb:
  desc: null
  value: true
verbose_plot:
  desc: null
  value: false
which_epoch:
  desc: null
  value: latest
which_timestamp:
  desc: null
  value: ''
