point_cloud_path = 'point_clouds'
dyn_feasible_points_path = 'dyn_feasible'
dyn_feasible_points_cropped_path = 'dyn_feasible_cropped'
dyn_infeasible_points_cropped_path = 'dyn_infeasible_cropped'
dyn_infeasible_points_path = "dyn_infeasible"
kin_feasible_configs_path = 'kin_feasible'
kin_infeasible_configs_path = 'kin_infeasible'
kin_feasible_cropped_configs_path = 'kin_feasible_cropped'
kin_infeasible_configs_path = 'kin_infeasible_cropped'
rest_pose_path = 'rest_pose'
num_points_in_point_cloud = 256
max_random_translation=0.05
num_rest_pose_initial_orn=10
rest_pose_drop_height=0.25
min_pc_point_height=0.015
min_dist_between_fingers=0.03
hand_ik_initial_guess_height=0.3
ik_attempts=3